export {
  GridUltraColumnMenu as GridColumnMenu,
  GRID_COLUMN_MENU_SLOTS_ULTRA as GRID_COLUMN_MENU_SLOTS,
  GRID_COLUMN_MENU_SLOT_PROPS_ULTRA as GRID_COLUMN_MENU_SLOT_PROPS,
} from './GridUltraColumnMenu';
